services:
  toppay:
    image: toppay:latest
    build: .
    env_file:
      - ./configs/.env
    volumes:
      - ./sms/code.txt:/sms/code.txt
      - ./pw-profile:/pw-profile
    restart: unless-stopped
